export default function PrivacyPage() {
  return (
    <div className="min-h-[calc(100vh-4rem)] py-20 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto">
        <h1 className="font-display text-4xl font-bold text-white mb-2">Privacy Policy</h1>
        <p className="text-[--text-muted] mb-10 text-sm">Last updated: February 5, 2026</p>

        <div className="space-y-10 text-sm leading-relaxed">
          <section>
            <h2 className="font-display text-lg font-semibold text-white mb-3">Introduction</h2>
            <p className="text-[--text-secondary]">
              PromptAI (&quot;we&quot;, &quot;our&quot;, or &quot;us&quot;) is committed to protecting your privacy. This Privacy Policy
              explains how we collect, use, disclose, and safeguard your information when you use our website,
              Chrome extension, and services.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-white mb-3">Information We Collect</h2>
            <h3 className="text-base font-medium text-white mb-2 mt-5">Account Information</h3>
            <p className="text-[--text-secondary] mb-3">When you create an account, we collect:</p>
            <ul className="list-disc pl-6 text-[--text-secondary] space-y-1.5">
              <li>Email address</li>
              <li>Password (stored securely using industry-standard hashing)</li>
              <li>Payment information (processed securely by Stripe)</li>
            </ul>
            <h3 className="text-base font-medium text-white mb-2 mt-5">Usage Data</h3>
            <p className="text-[--text-secondary] mb-3">When you use our services, we collect:</p>
            <ul className="list-disc pl-6 text-[--text-secondary] space-y-1.5">
              <li>Text you submit for prompt enhancement</li>
              <li>Enhanced prompts generated by our service</li>
              <li>Usage statistics (number of prompts enhanced, feature usage)</li>
              <li>Device identifiers for session management</li>
            </ul>
            <h3 className="text-base font-medium text-white mb-2 mt-5">Chrome Extension Data</h3>
            <p className="text-[--text-secondary] mb-3">Our Chrome extension collects:</p>
            <ul className="list-disc pl-6 text-[--text-secondary] space-y-1.5">
              <li>Text you select for enhancement (only when you actively use the extension)</li>
              <li>License key for authentication</li>
              <li>A unique device identifier stored locally in your browser</li>
            </ul>
            <p className="text-[--text-secondary] mt-3">
              The extension does NOT collect browsing history, personal data from web pages you visit,
              or any information unless you explicitly select text and request enhancement.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-white mb-3">How We Use Your Information</h2>
            <p className="text-[--text-secondary] mb-3">We use the information we collect to:</p>
            <ul className="list-disc pl-6 text-[--text-secondary] space-y-1.5">
              <li>Provide and maintain our prompt enhancement service</li>
              <li>Process your transactions and manage your subscription</li>
              <li>Send you service-related communications</li>
              <li>Improve and optimize our services</li>
              <li>Enforce our single-device policy per account</li>
              <li>Protect against fraud and unauthorized access</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-white mb-3">Data Storage and Security</h2>
            <p className="text-[--text-secondary] mb-3">We implement appropriate technical and organizational measures to protect your personal data:</p>
            <ul className="list-disc pl-6 text-[--text-secondary] space-y-1.5">
              <li>All data is transmitted using TLS/SSL encryption</li>
              <li>Passwords are hashed using industry-standard algorithms</li>
              <li>Payment data is processed by Stripe (PCI-DSS compliant)</li>
              <li>We use secure cloud infrastructure with regular security updates</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-white mb-3">Data Retention</h2>
            <p className="text-[--text-secondary]">
              We retain your account information for as long as your account is active. Prompt history
              may be retained for service improvement purposes. You can request deletion of your data
              by contacting us at support@promptai360.com.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-white mb-3">Data Sharing and Disclosure</h2>
            <p className="text-[--text-secondary] mb-3"><strong className="text-white">We do not sell, trade, or rent your personal information to third parties.</strong></p>
            <p className="text-[--text-secondary] mb-3">We share your data only with the following service providers, solely for the purposes described:</p>
            <ul className="list-disc pl-6 text-[--text-secondary] space-y-1.5">
              <li><strong className="text-white/80">OpenAI:</strong> We send the text you submit for enhancement to OpenAI&apos;s API to generate improved prompts. No personal account information is shared with OpenAI.</li>
              <li><strong className="text-white/80">Stripe:</strong> When you subscribe, your payment information is sent directly to Stripe for secure payment processing. We do not store your full card number.</li>
              <li><strong className="text-white/80">Google:</strong> If you choose to sign in with Google, we receive your email and name from Google OAuth. We do not access any other Google account data.</li>
            </ul>
            <p className="text-[--text-secondary] mt-3">We may also disclose your information if required by law, to protect our rights, or to comply with legal processes.</p>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-white mb-3">Third-Party Services</h2>
            <p className="text-[--text-secondary] mb-3">Our infrastructure uses the following services:</p>
            <ul className="list-disc pl-6 text-[--text-secondary] space-y-1.5">
              <li><strong className="text-white/80">Vercel:</strong> Website hosting (processes server logs)</li>
              <li><strong className="text-white/80">Railway:</strong> Backend API hosting (processes server logs)</li>
            </ul>
            <p className="text-[--text-secondary] mt-3">These providers may process technical data (IP addresses, request logs) as part of their hosting services, subject to their own privacy policies.</p>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-white mb-3">Your Rights</h2>
            <p className="text-[--text-secondary] mb-3">You have the right to:</p>
            <ul className="list-disc pl-6 text-[--text-secondary] space-y-1.5">
              <li>Access your personal data</li>
              <li>Correct inaccurate data</li>
              <li>Request deletion of your data</li>
              <li>Export your data</li>
              <li>Opt out of marketing communications</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-white mb-3">Cookies</h2>
            <p className="text-[--text-secondary]">We use essential cookies to maintain your session and preferences. We do not use tracking cookies for advertising purposes.</p>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-white mb-3">Children&apos;s Privacy</h2>
            <p className="text-[--text-secondary]">Our services are not intended for children under 13 years of age. We do not knowingly collect personal information from children under 13.</p>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-white mb-3">Changes to This Policy</h2>
            <p className="text-[--text-secondary]">We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the &quot;Last updated&quot; date.</p>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-white mb-3">Contact Us</h2>
            <p className="text-[--text-secondary]">
              If you have any questions about this Privacy Policy, please contact us at:{" "}
              <a href="mailto:support@promptai360.com" className="text-teal-400 hover:text-teal-300 transition-colors">support@promptai360.com</a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
